import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })
import Link from 'next/link'

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img />
          <Link href='/' legacyBehavior>
            <a>Home</a>
          </Link>

          <Link href='/events' legacyBehavior>
            <a>Events</a>
          </Link>

          <Link href='/AboutUs' legacyBehavior>
            <a>About Us</a>
          </Link>
        </nav>
      </header>


      <main className={styles.main}>

        {data.map((ev, i) => (
          <Link href={`/events/${ev.id}`} key={i} legacyBehavior>
            <a>
              <Image src={ev.image} alt={ev.title} width={200} height={200} />
              <h2>{ev.title}</h2>
              <p>
                {ev.description}
              </p>
            </a>
          </Link>
        )
        )}


      </main>

      <footer>
        <p>Copy Right</p>
      </footer>
    </>
  )
}
export const getServerSideProps = async (ctx) => {
  const { events_categories, allEvents } = await import('../data/data.json')


  return {
    props: {
      data: events_categories
    }
  }
}